apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  name: default-dsci
spec:
  applicationsNamespace: opendatahub
  devFlags:
    logmode: production
  monitoring:
    managementState: Managed
    metrics:
      resources:
        cpulimit: 500m
        cpurequest: 100m
        memorylimit: 512Mi
        memoryrequest: 256Mi
      storage:
        retention: 1d
        size: 5Gi
    namespace: opendatahub
    traces:
      sampleRatio: "0.1"
      storage:
        backend: pv
  serviceMesh:
    controlPlane:
      metricsCollection: Istio
      name: data-science-smcp
      namespace: istio-system
    managementState: Removed    
  trustedCABundle:
    customCABundle: ""
    managementState: Managed
