apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: llamastack-custom-distribution
  namespace: llamastack
spec:
  replicas: 1
  server:
    containerSpec:
      env:
        - name: VLLM_URL
          value: 'https://llama-32-3b-instruct-llamastack.apps.gmontero419.devcluster.openshift.com/v1'
        - name: INFERENCE_MODEL
          value: llama-32-3b-instruct
        - name: MILVUS_DB_PATH
          value: ~/.llama/milvus.db
        - name: VLLM_TLS_VERIFY
          value: 'false'
        - name: FMS_ORCHESTRATOR_URL
          value: 'http://localhost:1234'
      name: llama-stack
      port: 8321
    distribution:
      name: 'rh-dev'
    storage:
      size: 20Gi
      mountPath: /opt/app-root/src/.llama/distributions/rh/
